### ISSUE TITLE
Unable to see system update option in Asus Zenfone max pro m2

### ISSUE THREAD

**Issue by GurramLakshmiNarayana** [Havoc-OS/OTA#3]
I recently installed **Havoc-OS-v3.9-20200915-X01BD-Official-GApps** in my Asus Zenfone Max Pro M2. Now **Havoc-OS-v3.9-20200927-X01BD-Official-GApps** has been released so i thought of checking for system update but i didn't find that option.
When i do search in setting, it shows system update option but when i select it it again goes to system settings.
Please help me in properly updating my device to latest build.

**Comment by Blacksuan19** [comment]
OTA update is not available in the rom yet

**Comment by GurramLakshmiNarayana** [comment]
Just out of curiosity i wanted to know that is it planned in future releases?

**Comment by Blacksuan19** [comment]
Yes probably
